name: CI

on: [push, pull_request]

env: 
  DATABASE_URL: "https://fake.com"

jobs:
  builds:
    runs_on: ubuntu_latest

    steps:
      - name: Checkout
        uses: action/ checkout@v2

      - name: Install Dependencies
        run: npm Install
      
      - name: Typecheck
        run: npm run Typecheck
      
      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
      